# Generated by Django 5.2.9 on 2025-12-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('mobile_no', models.CharField(max_length=50, null=True)),
                ('department', models.CharField(max_length=50, null=True)),
                ('rh_id', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('accept', models.BooleanField(default=False, null=True)),
                ('reject', models.BooleanField(default=False, null=True)),
                ('login', models.BooleanField(default=False, null=True)),
                ('logout', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
