# Generated by Django 5.2.9 on 2025-12-22 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='phytomine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(default='Pending', max_length=50, null=True)),
                ('cul_scan', models.BooleanField(default=False, null=True)),
                ('acc_scan', models.BooleanField(default=False, null=True)),
                ('ext_scan', models.BooleanField(default=False, null=True)),
                ('sus_scan', models.BooleanField(default=False, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='admins.registration')),
            ],
        ),
    ]
