# Generated by Django 5.2.9 on 2025-12-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_phytomine'),
    ]

    operations = [
        migrations.AddField(
            model_name='phytomine',
            name='extraction_eff',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='final_fern_biomass',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='final_soil_ree',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='growth_duration',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='harvested_biomass',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='initial_fern_biomass',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='initial_soil_ree',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='plant_ree_conc',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='soil_ree_conc',
            field=models.FloatField(null=True),
        ),
    ]
