# Generated by Django 5.2.9 on 2025-12-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_phytomine_extraction_eff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phytomine',
            name='admins_f_rep_view',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='admins_f_report',
            field=models.FileField(blank=True, null=True, upload_to='Report/'),
        ),
    ]
