# Generated by Django 5.2.9 on 2025-12-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_phytomine_admins_f_rep_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phytomine',
            name='cul_decrypt',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='cul_decrypt_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='cul_get_key',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='e_extraction_eff',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='e_final_fern_biomass',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='e_final_soil_ree',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='e_growth_duration',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='e_harvested_biomass',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='e_initial_fern_biomass',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='e_initial_soil_ree',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='e_plant_ree_conc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='e_soil_ree_conc',
            field=models.TextField(null=True),
        ),
    ]
