# Generated by Django 5.2.9 on 2025-12-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_phytomine_cul_decrypt_phytomine_cul_decrypt_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phytomine',
            name='acc_decrypt',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='acc_decrypt_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='acc_get_key',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='biomass_increase',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='e_biomass_increase',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='e_growth_eff',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='e_growth_rate',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='growth_eff',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='growth_rate',
            field=models.FloatField(null=True),
        ),
    ]
