# Generated by Django 5.2.9 on 2025-12-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_phytomine_acc_decrypt_phytomine_acc_decrypt_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phytomine',
            name='baf',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='e_baf',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='e_total_metal',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='e_uptake',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='ext_decrypt',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='ext_decrypt_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='ext_get_key',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='total_metal',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='uptake',
            field=models.FloatField(null=True),
        ),
    ]
