# Generated by Django 5.2.9 on 2025-12-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_phytomine_baf_phytomine_e_baf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phytomine',
            name='loss',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='recovered_metal',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='recovery',
            field=models.FloatField(null=True),
        ),
    ]
