# Generated by Django 5.2.9 on 2025-12-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_phytomine_loss_phytomine_recovered_metal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phytomine',
            name='e_loss',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='e_recovered_metal',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='e_recovery',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='sus_decrypt',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='sus_decrypt_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='sus_get_key',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
