# Generated by Django 5.2.9 on 2025-12-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0009_phytomine_e_loss_phytomine_e_recovered_metal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phytomine',
            name='env_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='reduction',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='safety_index',
            field=models.FloatField(null=True),
        ),
    ]
