# Generated by Django 5.2.9 on 2026-04-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0010_phytomine_env_status_phytomine_reduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phytomine',
            name='acc_signed_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='cul_signed_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='ext_signed_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='phytomine',
            name='sus_signed_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
