# Generated by Django 5.2.9 on 2026-04-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0011_phytomine_acc_signed_by_phytomine_cul_signed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phytomine',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
