# Generated by Django 5.2.9 on 2026-04-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0012_phytomine_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='phytomine',
            name='soil_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
