# Generated by Django 5.2.9 on 2026-04-02 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0013_phytomine_soil_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='phytomine_insights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insights_text', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='admins.phytomine')),
            ],
        ),
    ]
