# Generated by Django 5.2.9 on 2026-04-02 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0014_phytomine_insights'),
    ]

    operations = [
        migrations.AddField(
            model_name='phytomine',
            name='is_insights_generated',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='phytomine',
            name='project_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='phytomine_insights',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='admins.phytomine', to_field='project_id'),
        ),
    ]
