# Generated by Django 5.2.9 on 2026-05-27 11:35
# MANUALLY EDITED: Uses RunPython to check column/index existence before altering.
# Works on all MySQL versions. Safe to re-run after partial failure.

import uuid
from django.db import migrations, models, connection


def add_column_if_not_exists(apps, schema_editor):
    """Add qr_code and tracking_id columns only if they don't already exist."""
    with connection.cursor() as cursor:
        # Check if qr_code column exists
        cursor.execute("""
            SELECT COUNT(*) FROM information_schema.columns
            WHERE table_schema = DATABASE()
            AND table_name = 'admins_phytomine'
            AND column_name = 'qr_code'
        """)
        if cursor.fetchone()[0] == 0:
            cursor.execute(
                "ALTER TABLE admins_phytomine ADD COLUMN qr_code VARCHAR(100) NULL;"
            )

        # Check if tracking_id column exists
        cursor.execute("""
            SELECT COUNT(*) FROM information_schema.columns
            WHERE table_schema = DATABASE()
            AND table_name = 'admins_phytomine'
            AND column_name = 'tracking_id'
        """)
        if cursor.fetchone()[0] == 0:
            cursor.execute(
                "ALTER TABLE admins_phytomine ADD COLUMN tracking_id CHAR(32) NULL;"
            )


def populate_tracking_ids(apps, schema_editor):
    """Assign a unique UUID to every existing phytomine row that has no tracking_id.
    Uses raw SQL because the ORM frozen state at migration time doesn't know tracking_id yet.
    """
    with connection.cursor() as cursor:
        # Fetch IDs of all rows that need a tracking_id
        cursor.execute(
            "SELECT id FROM admins_phytomine WHERE tracking_id IS NULL OR tracking_id = '';"
        )
        rows = cursor.fetchall()
        for (row_id,) in rows:
            new_uuid = uuid.uuid4().hex  # 32-char hex string, matches CHAR(32)
            cursor.execute(
                "UPDATE admins_phytomine SET tracking_id = %s WHERE id = %s;",
                [new_uuid, row_id]
            )


def add_unique_constraint(apps, schema_editor):
    """Make tracking_id NOT NULL and add unique index if not already present."""
    with connection.cursor() as cursor:
        # First make it NOT NULL
        cursor.execute("""
            ALTER TABLE admins_phytomine
            MODIFY COLUMN tracking_id CHAR(32) NOT NULL;
        """)

        # Check if unique index already exists
        cursor.execute("""
            SELECT COUNT(*) FROM information_schema.statistics
            WHERE table_schema = DATABASE()
            AND table_name = 'admins_phytomine'
            AND index_name = 'admins_phytomine_tracking_id_uniq'
        """)
        if cursor.fetchone()[0] == 0:
            cursor.execute("""
                ALTER TABLE admins_phytomine
                ADD UNIQUE INDEX admins_phytomine_tracking_id_uniq (tracking_id);
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0015_phytomine_is_insights_generated_and_more'),
    ]

    operations = [
        # Step 1: Add columns only if missing (safe after partial failure)
        migrations.RunPython(add_column_if_not_exists, migrations.RunPython.noop),

        # Step 2: Populate unique UUIDs for existing rows
        migrations.RunPython(populate_tracking_ids, migrations.RunPython.noop),

        # Step 3: Apply NOT NULL + unique index
        migrations.RunPython(add_unique_constraint, migrations.RunPython.noop),

        # Step 4: Update Django's ORM state to match the actual DB schema
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='phytomine',
                    name='qr_code',
                    field=models.ImageField(blank=True, null=True, upload_to='qr/'),
                ),
                migrations.AlterField(
                    model_name='phytomine',
                    name='tracking_id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
            ],
            database_operations=[],  # Already done above via RunPython
        ),
    ]
